### ISSUE TITLE
frontend endpointok tesztelése

### ISSUE THREAD

**Issue by markraven** [markraven/Wellness-Badges-#16]
- [x] Add Product Service

- [ ] Book out

- [x] Book room

- [x] Buy

- [x] Check in

- [ ] Reservation
Fentebbi endpointok tesztelése a frontend környezetben

**Comment by pichaccu** [comment]
Tesztelés során kiderült hogy a price hiányzik belőle. Javításra ki lett írva. #18

**Comment by pichaccu** [comment]
Tesztelés során kiderült hogy a nem adjuk vissza a lefoglalt szoba számát. Javításra ki lett írva. #21

**Comment by markraven** [comment]
A tesztelés során reponse feldolgozással kapcsolatos problémába ütköztünk.
