### ISSUE TITLE
Add Product Service Bugjavítás

### ISSUE THREAD

**Issue by pichaccu** [markraven/Wellness-Badges-#18]
Hiányzik belőle a price mező.

**Comment by mikimi1233** [comment]
A hiba javításra került, újabb tesztelés szükséges. Észrevétel: rossz helyre került a feltöltött fálj, ezért az eredetit kiveszem és az új javítottat a megfelelő helyre teszem.

**Comment by pichaccu** [comment]
Újra tesztelés megtörtént, működik.
