### ISSUE TITLE
Guest form nem tesz új table rowba

### ISSUE THREAD

**Issue by Beives** [markraven/Wellness-Badges-#22]
Check in formnál az új guest felvételénél nem új sorba töri az adatokat

**Comment by mikimi1233** [comment]
A hiba részleges javítása megtörtént. Az endpoint branchben lévő kódban a változásokat átírtam.
Részleges működés: Az adatokat új sorba töri, azonban a name-et többször megismétli. Sajnos a javítása nem sikerült, viszont értem miért van gond vele.
Az element inputoknál felcserélés történt, ennek javítása megtörtént.
